### ISSUE TITLE
Rule book

### ISSUE THREAD

**Issue by nateJames196** [nateJames196/cactpot#13]
A function that displays the instructions for the game needs to be implemented as part of the main menu (see issue #6 ). Shouldn't be difficult.

**Comment by clc24707** [comment]
#include <iostream>
using namespace std;

void printInstructions();

int main()
{
printInstructions();

return 0;

}

void printInstructions()
{
cout << "\tRules...\n" endl;
cout << "Every lottery ticket has nine cells – a 3x3 matrix, and eight lines – vertical, horizontal, and diagonal.
Each cell hides a random number from one to nine – no repeats. When a game starts, eight of these nine numbers are hidden." << endl;
cout << "1. Select Three Numbers: To begin, you must select three cells from the eight with hidden values on the ticket, and uncover their numbers." endl;
cout << "2. Select a Line: Next, the you must select one of eight lines ─ vertical, horizontal, or diagonal." << endl;
cout << "3. Receive a Reward: Once you have selected a line, all its numbers are uncovered and you are awarded Gold Point Rewards." endl;
cout << "You are able to play as many times as you wish.\n" <<"Have Fun!" << endl;
}
