### ISSUE TITLE
Display high score

### ISSUE THREAD

**Issue by nateJames196** [nateJames196/cactpot#14]
A function that displays the current highest score needs to be implemented as part of the main menu (see #6 ).

**Comment by bandidoluch** [comment]
*/
//header files(s)
void DisplayHighscore;

ifstream infile;  //file open 
infile.open("highscore.txt");
if (getline(infile, username))
{
	infline.ignore();
}
else
cout << "There Is No Highscore....." << endl;

infile.close(); //file close

**Comment by bandidoluch** [comment]
Display highscore 

*/
//header files(s)
#include <iostream>
#include <fstream>
#include <string>
using namespace std;


int Score;
string userName;


void DisplayHighscore();

void DisplayHighscore()
{    

	
	ifstream infile;  //file open 
	infile.open("highscore.txt");

	{
	
	}
	if (cin >> userName)
		fstream 

		


		

		}




     else
     cout << "There Is No Highscore....." << endl;

     infile.close(); //file close

}
