### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by nateJames196** [nateJames196/cactpot#6]
The main menu needs to be created

**Comment by clc24707** [comment]
#include <iostream>
using namespace std;

int main()
{
const minOP = 1;
const maxOP =4;
int userOP;

do
{
cout << "\t\tCactpot Main Menu\n"" << endl;
cout<< "1) See Rules" << endl;
cout << "2) Play Game" << endl;
cout << "3)See Highest Score" << endl;
cout << "4)Quit" << endl;
cin >> userOP

while(userOP >= minOP && userOP <= maxOP)
{
switch(userOP)
{
case 1: printInstruction();
break;
case 2:...;
break;
case 3:...;
break;
case 4: cout << "Quitting game...";
break;
}
}

if (userOP < minOP || userOP > maxOP)
cout << "Error. Must choose from 1 to 4"
}while(userOP < minOP || user OP > maxOP);
